packages:
  - "playnite-insights"
  - "playwright"
  - "packages/@playnite-insights/lib"
  - "packages/@playnite-insights/infra"
  - "packages/@playnite-insights/core"
  - "packages/@playnite-insights/testing"
  - "packages/@playatlas/auth"
  - "packages/@playatlas/game-library"
  - "packages/@playatlas/game-note"
  - "packages/@playatlas/game-session"
  - "packages/@playatlas/common"
  - "packages/@playatlas/system"
  - "packages/@playatlas/bootstrap"
  - "packages/@playatlas/playnite-integration"
  - "packages/integration-testing"
injectWorkspacePackages: true
