### Get all companies
GET {{protocol}}://{{host}}/api/company
Content-Type: {{contentType}}

### Get all platforms
GET {{protocol}}://{{host}}/api/platform
Content-Type: {{contentType}}

### Get all genres
GET {{protocol}}://{{host}}/api/genre
Content-Type: {{contentType}}

### Get all games
GET {{protocol}}://{{host}}/api/game
Content-Type: {{contentType}}

### Get dashboard page data
GET {{protocol}}://{{host}}/api/dash
Content-Type: {{contentType}}