### Get game by id
GET {{protocol}}://{{host}}/api/developer
Content-Type: {{contentType}}

### Get all games
GET {{protocol}}://{{host}}/api/game
Content-Type: {{contentType}}

### Get dashboard page data
GET {{protocol}}://{{host}}/api/dash
Content-Type: {{contentType}}