### Get all games (paginated)
GET {{protocol}}://{{host}}/api/playnite-games/home?page=1&page_size=50
Content-Type: {{contentType}}

### Get game by id
GET {{protocol}}://{{host}}/api/playnite-games/game-200
Content-Type: {{contentType}}