BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS `instance_authentication` (
  `Id` INTEGER PRIMARY KEY CHECK (id = 1),
  `PasswordHash` TEXT NOT NULL,
  `Salt` TEXT NOT NULL,
  `CreatedAt` TEXT DEFAULT CURRENT_TIMESTAMP,
  `LastUpdatedAt` TEXT DEFAULT CURRENT_TIMESTAMP
);

COMMIT;