BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS `synchronization_id` (
  `Id` INTEGER PRIMARY KEY CHECK (Id = 1),
  `SyncId` TEXT NOT NULL,
  `CreatedAt` TEXT DEFAULT CURRENT_TIMESTAMP,
  `LastUsedAt` TEXT DEFAULT CURRENT_TIMESTAMP
);

COMMIT;