FROM node:alpine AS build

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

FROM node:alpine AS run

# Create user and group
RUN addgroup -S playnite-insights && adduser -S -G playnite-insights playnite-insights

WORKDIR /app
ENV WORK_DIR=/app
ENV NODE_ENV=development
ENV BODY_SIZE_LIMIT=256M

COPY --chown=playnite-insights:playnite-insights --from=build /app/node_modules .

# Copy source files into application directory
COPY --chown=playnite-insights:playnite-insights . /app

EXPOSE 3000

USER playnite-insights

ENTRYPOINT ["sh", "docker/init.sh", "npx", "vite", "dev", "--host"]