services:
  app-playwright:
    build:
      context: .
      target: playwright
    container_name: app-playwright
    environment:
      BASE_URL: 'http://app-stage:3000'
    volumes:
      - playnite-insights-playwright-results:/app/playwright-report
    depends_on:
      - app-test-results
    networks:
      - app-nw

  app-test-results:
    image: nginx:alpine
    container_name: test-results
    volumes:
      - playnite-insights-playwright-results:/usr/share/nginx/html/playwright:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - services-ipv6

volumes:
  playnite-insights-playwright-results:

networks:
  services-ipv6:
    external: true
  app-nw:
    external: true
