### Get home page game data (paginated)
GET {{protocol}}://{{host}}/api/home?page=1&page_size=50
Content-Type: {{contentType}}

### Get game by id
GET {{protocol}}://{{host}}/api/game/f0f93674-2cba-440c-b3da-56f109aced0d
Content-Type: {{contentType}}

### Get dashboard page data
GET {{protocol}}://{{host}}/api/dash
Content-Type: {{contentType}}