### Get library manifest
GET {{protocol}}://{{host}}/api/sync/manifest
Content-Type: {{contentType}}

### Run action on Playnite Host
POST {{protocol}}://{{host}}/api/action
Content-Type: {{contentType}}

{
  "action": "screenshot"
}

### Get all available screenshots
GET {{protocol}}://{{host}}/api/assets/image/screenshot/all
Content-Type: {{contentType}}

### Get all companies
GET {{protocol}}://{{host}}/api/company
Content-Type: {{contentType}}

### Get all platforms
GET {{protocol}}://{{host}}/api/platform
Content-Type: {{contentType}}

### Get all genres
GET {{protocol}}://{{host}}/api/genre
Content-Type: {{contentType}}

### Get all games
GET {{protocol}}://{{host}}/api/game
Content-Type: {{contentType}}

### Get library metrics
GET {{protocol}}://{{host}}/api/library/metrics
Content-Type: {{contentType}}

### Get all game sessions
GET {{protocol}}://{{host}}/api/session
Content-Type: {{contentType}}

### Get all game sessions for today
GET {{protocol}}://{{host}}/api/session/recent
Content-Type: {{contentType}}

### Get all game sessions for today
GET {{protocol}}://{{host}}/api/extension-registration
Content-Type: {{contentType}}

### Register instance
POST {{protocol}}://{{host}}/api/auth/register
Content-Type: {{contentType}}

{
  "password": "test123"
}

### Login instance
POST {{protocol}}://{{host}}/api/auth/login
Content-Type: {{contentType}}

{
  "password": "test123"
}

### Check health
GET {{protocol}}://{{host}}/api/health
Content-Type: {{contentType}}
Authorization: Bearer 2d2749b736fda1e2c9387e4f16b4a47a80e25eb2d42c2da9150c71bb17ca4033