### Get library manifest
GET {{protocol}}://{{host}}/api/sync/manifest
Content-Type: {{contentType}}

### Get all companies
GET {{protocol}}://{{host}}/api/company
Content-Type: {{contentType}}

### Get all platforms
GET {{protocol}}://{{host}}/api/platform
Content-Type: {{contentType}}

### Get all genres
GET {{protocol}}://{{host}}/api/genre
Content-Type: {{contentType}}

### Get all games
GET {{protocol}}://{{host}}/api/game
Content-Type: {{contentType}}

### Get library metrics
GET {{protocol}}://{{host}}/api/library/metrics
Content-Type: {{contentType}}

### Get all game sessions
GET {{protocol}}://{{host}}/api/session
Content-Type: {{contentType}}

### Get all game sessions for today
GET {{protocol}}://{{host}}/api/session/recent
Content-Type: {{contentType}}

### Create a session
POST {{protocol}}://{{host}}/api/session/open
Content-Type: {{contentType}}

{
  "SessionId": "{{$uuid}}",
  "GameId": "35ae3f82-98d6-42f9-933e-243c26b48147",
  "StartTime": "2025-07-28T23:51:35.5476026Z"
}

### Close a session
POST {{protocol}}://{{host}}/api/session/close
Content-Type: {{contentType}}

{
  "SessionId": "{{$uuid}}",
  "GameId": "35ae3f82-98d6-42f9-933e-243c26b48147",
  "StartTime": "2025-07-28T23:51:35.5476026Z",
  "EndTime": "2025-07-28T23:59:35.5476026Z",
  "Duration": 200,
  "Status": "closed"
}